// <auto-generated />
using System;
using BusinessToolbox.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BusinessToolbox.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BusinessToolbox.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f1a7d6e4-4c4c-4e4c-8e4c-1c4c4e4c4c4c"),
                            Icon = "🍎",
                            Name = "Comida"
                        },
                        new
                        {
                            Id = new Guid("f2a7d6e4-4c4c-4e4c-8e4c-1c4c4e4c4c4c"),
                            Icon = "🚗",
                            Name = "Transporte"
                        },
                        new
                        {
                            Id = new Guid("f3a7d6e4-4c4c-4e4c-8e4c-1c4c4e4c4c4c"),
                            Icon = "💡",
                            Name = "Servicios"
                        },
                        new
                        {
                            Id = new Guid("f4a7d6e4-4c4c-4e4c-8e4c-1c4c4e4c4c4c"),
                            Icon = "🎬",
                            Name = "Entretenimiento"
                        },
                        new
                        {
                            Id = new Guid("f5a7d6e4-4c4c-4e4c-8e4c-1c4c4e4c4c4c"),
                            Icon = "📦",
                            Name = "Otros"
                        });
                });

            modelBuilder.Entity("BusinessToolbox.Domain.Entities.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("BusinessToolbox.Domain.Entities.Expense", b =>
                {
                    b.HasOne("BusinessToolbox.Domain.Entities.Category", "Category")
                        .WithMany("Expenses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BusinessToolbox.Domain.Entities.Category", b =>
                {
                    b.Navigation("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
